#!/usr/bin/env python3
"""Emit the built-in font registry from a list of baked font names.

    gen_font_registry.py ui16 helvR12 ... > font_registry.c

Every baked font header declares its atlas as `static const`, so whichever
translation unit includes it gets its own copy of the pixels. Funnelling
them all through this one generated TU is what keeps 1.25 MiB of atlas
from being duplicated into every demo that wants a font.

The registry keeps mutable copies of the surf_font structs so a device
backend can re-home each atlas into DMA-able RAM once at startup
(surf_font_builtin_prepare) and have every later lookup see the prepared
version.
"""
import sys

names = sys.argv[1:]
if not names:
    sys.exit("usage: gen_font_registry.py NAME...")

w = sys.stdout.write
w("/* Generated by tools/gen_font_registry.py — do not edit. */\n")
w('#include <string.h>\n\n#include "surfer.h"\n\n')
for n in names:
    w('#include "font_%s.h"\n' % n)

w("\nstatic const struct {\n    const char *name;\n"
  "    const surf_font *font;\n} builtins[] = {\n")
for n in names:
    w('    {"%s", &surf_font_%s},\n' % (n, n))
w("};\n\n#define NBUILTIN ((int)(sizeof builtins / sizeof builtins[0]))\n\n")

w("""/* mutable copies: prepare() may swap each atlas for a DMA-able one */
static surf_font fonts[NBUILTIN];
static bool loaded;

static void load_once(void)
{
    if (loaded)
        return;
    for (int i = 0; i < NBUILTIN; i++)
        fonts[i] = *builtins[i].font;
    loaded = true;
}

int surf_font_builtin_count(void)
{
    return NBUILTIN;
}

const char *surf_font_builtin_name(int idx)
{
    return (idx >= 0 && idx < NBUILTIN) ? builtins[idx].name : NULL;
}

const surf_font *surf_font_builtin_at(int idx)
{
    if (idx < 0 || idx >= NBUILTIN)
        return NULL;
    load_once();
    return &fonts[idx];
}

const surf_font *surf_font_builtin(const char *name)
{
    if (!name)
        return NULL;
    load_once();
    for (int i = 0; i < NBUILTIN; i++)
        if (strcmp(builtins[i].name, name) == 0)
            return &fonts[i];
    return NULL;
}

void surf_font_builtin_prepare(surf_font_prepare_fn fn)
{
    load_once();
    if (!fn)
        return;
    for (int i = 0; i < NBUILTIN; i++)
        fn(&fonts[i].atlas);
}
""")
